### ISSUE TITLE
JWT cache not shared across endpoints ?

### ISSUE THREAD

**Issue by cboitel** [krakend/krakend-jose#78]
Configured Krakend to cache JWKS keys:
```
    extra_config:
      github.com/devopsfaith/krakend-jose/validator:
        alg: RS256
        jwk-url: "http://myidp/jwks"
        issuer: "http://myidp"
        propagate-claims:
        - ["sub", "x-user"]
        disable_jwk_security: true # only for non https jwk-url
        cache: true
        cache_duration: 300
```

Although cache is enabled, we see multiple retrieval requests of JWKS from krakend host to the identity provider aka IDP. Tests are showing cache is effective but per end-point and every end-point loads its cache at startup.

As a consequence:
1.  we get as much requests as different endpoints every 15min (cache_duration fails to be effective, see my other issue)
2.  we get a bunch of JWKS requests each time a new Krakend running instance is started.
3.  this is putting extra load (and cost when hosted on pubic cloud providers) on our IDP and its front LB
